#pragma once

#include "Command.hpp"
#include "InternetCard.hpp"

// concrete classes, extend class Command, generated by uniform macro
GEN_COMMAND(InternetCard, Read, internetCard, sendIn);
GEN_COMMAND(InternetCard, Write, internetCard, recvFrom);
