#pragma once

#include "Command.hpp"
#include "Ram.hpp"

// concrete classes, extend class Command, generated by uniform macro
GEN_COMMAND(Ram, Read, internetCard, read);
GEN_COMMAND(Ram, Write, internetCard, write);
