#pragma once

#include "Command.hpp"
#include "SoundCard.hpp"

// classes, extend class Command, generated by uniform macro
GEN_COMMAND(SoundCard, Read, internetCard, play);
GEN_COMMAND(SoundCard, Write, internetCard, record);
